version: "3.2"

networks:
  demo:

services:

  cf:
    image: cfdemo3
    environment:
      - TZ=America/Los_Angeles
    networks:
      - demo
    environment:
      - myapp_env=dev

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - "cf"
    networks:
      - demo
    ports:
      - "80:80"
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - type: bind
        source: .\nginx\nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

  redis:
    image: redis:latest
    networks:
      - demo
    environment:
      - TZ=America/Los_Angeles